version: '3.8'

services:
  lapdev:
    build: .
    container_name: lapdev-controller
    ports:
      - "8080:80"
      - "8443:443"
      - "6123:6123"
    volumes:
      - ./lapdev.conf:/etc/lapdev.conf
      - ssl_certs:/etc/lapdev/ssl
      - lapdev_data:/var/lib/lapdev
      - logs:/var/log
    environment:
      DB_HOST: postgres-server
      DB_PORT: 5432
      DB_NAME: lapdev
      DB_USER: subaga
      DB_PASSWORD: subaga2025
    networks:
      - dokploy-network
    restart: unless-stopped

volumes:
  ssl_certs:
  lapdev_data:
  logs:

networks:
  dokploy-network:
    external: true